### ISSUE TITLE
Home Details Screen

### ISSUE THREAD

**Issue by crebollarramirez** [mikxvii/JMGWorkScape#11]
- [x]  Add page design
- [x] Add information about like image, name, and day of the week.
- [x] Add the "Create Invoice" button
- [x] Add the "Take Me There" button.
- [x] Add the remove button. 
- [x] Add the Back button which should take you back to the HomeScreen when pressed.

**Comment by mikxvii** [comment]
Create Invoice is the last part of the HomeDetailsScreen, refer to figma design and look into how to create a pdf and be able to send in app or download.
