### ISSUE TITLE
Route Screen

### ISSUE THREAD

**Issue by crebollarramirez** [mikxvii/JMGWorkScape#8]
- [x] Have proper background set
- [x] Have the title which uses real day of the week 
- [x] VStack list of houses for that day of the week
- [x] Have add button visual 
- [ ]  Have go button visual
- [x] Back button and when click, it takes us back to home

**Comment by mikxvii** [comment]
The List is created with all of the houses at the moment, but we should be able to take in a list of houses and filter the houses by the current day, and have them be displayed. The title of the screen should also be updated accordingly. This filtering should occur when the screen is opened. There is a function that fetches the current weekday and should be used for the aforementioned features of the screen. We can worry about the add button and go button after the meeting on August 1 (Thursday).
